### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by abbbi** [tizbac/pmoxs3backuproxy#22]
ive seen these occasionally now 2 or 3 times, its not quite reproducible and looks like a race condition. It was the reason for my pull request to add timestamps ..

Sometimes the PVE seems to be so fast with requesting tickets that there may be a race condition while
assigning a ticket:

```
2024/08/11 00:24:57 [DEBUG] Request://api2/json/access/ticket
2024/08/11 00:24:57 [DEBUG] {"data":{"CSRFPreventionToken":"35h235h23yh23","ticket":"RpqUfZlzoNNYmkpRStNthwVGVszkgtVDeahxQZFFnsDYGpiqoJwVguyPgKelCKwT","username":"HYLOYMOF5GPB1E68H6GU@pbs"}}
2024/08/11 00:24:57 [DEBUG] Request:/api2/json/admin/datastore/backups/status
2024/08/11 00:24:59 [DEBUG] Request:/api2/json/access/ticket
2024/08/11 00:24:59 [DEBUG] Request:/api2/json/access/ticket
2024/08/11 00:24:59 [DEBUG] Content-Type=application/x-www-form-urlencoded
2024/08/11 00:24:59 [DEBUG] Content-Length=89
2024/08/11 00:24:59 [DEBUG] Content-Type=application/x-www-form-urlencoded
2024/08/11 00:24:59 [DEBUG] Te=deflate,gzip;q=0.3
2024/08/11 00:24:59 [DEBUG] Keep-Alive=300
2024/08/11 00:24:59 [DEBUG] Connection=Keep-Alive, TE
2024/08/11 00:24:59 [DEBUG] Accept-Encoding=gzip
2024/08/11 00:24:59 [DEBUG] Te=deflate,gzip;q=0.3
2024/08/11 00:24:59 [DEBUG] Keep-Alive=300
2024/08/11 00:24:59 [DEBUG] Connection=Keep-Alive, TE
2024/08/11 00:24:59 [DEBUG] Accept-Encoding=gzip
2024/08/11 00:24:59 [DEBUG] User-Agent=libwww-perl/6.52
2024/08/11 00:24:59 [DEBUG] Content-Length=89
2024/08/11 00:24:59 [DEBUG] User-Agent=libwww-perl/6.52
2024/08/11 00:24:59 [DEBUG] {"data":{"CSRFPreventionToken":"35h235h23yh23","ticket":"XHfcmLdyMGgYYKggRNcwKXqiDHJALakKBcWnaovrAqkoTCOMeYTcMzAGsWduSiFl","username":"HYLOYMOF5GPB1E68H6GU@pbs"}}
2024/08/11 00:24:59 [DEBUG] {"data":{"CSRFPreventionToken":"35h235h23yh23","ticket":"btPkButejuzQmqxLIVRSgAVmSDrkDqAiCkeCocJocbQCgdEGFvyRFmpISbQuoqfG","username":"HYLOYMOF5GPB1E68H6GU@pbs"}}
2024/08/11 00:24:59 [DEBUG] Request:/api2/json/admin/datastore
2024/08/11 00:24:59 [DEBUG] Request:/api2/json/admin/datastore
2024/08/11 00:24:59 [DEBUG] List buckets
2024/08/11 00:24:59 [DEBUG] List buckets
2024/08/11 00:25:00 [DEBUG] Request://api2/json/access/ticket
2024/08/11 00:25:00 [DEBUG] Request://api2/json/access/ticket
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 370 [running]:
main.(*Server).ServeHTTP(0xc0002a9500, {0x956df8, 0xc00028c380}, 0xc00037cd80)
        /home/abi/pmoxs3backuproxy/cmd/pmoxs3backuproxy/main.go:584 +0x379b
net/http.serverHandler.ServeHTTP({0x955c78?}, {0x956df8?, 0xc00028c380?}, 0x6?)
        /home/abi/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000196cf0, {0x9579c8, 0xc0002ce1e0})
        /home/abi/go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        /home/abi/go/src/net/http/server.go:3285 +0x4b4
```

**Comment by tizbac** [comment]
I wrongly assumed map to be threadsafe, it's not it being fast , but doing
two requests at same time
Also ticket expiring potentially broken

Il dom 11 ago 2024, 00:28 Michael Ablassmeier ***@***.***> ha
scritto:

**Comment by abbbi** [comment]
yes, running it with -race shows clearly:

```
==================
WARNING: DATA RACE
Write at 0x00c000115b90 by goroutine 104:
  runtime.mapassign_faststr()
      /home/abi/go/src/runtime/map_faststr.go:203 +0x0
  main.(*Server).ServeHTTP()
      /home/abi/pmoxs3backuproxy/cmd/pmoxs3backuproxy/main.go:584 +0x7e3e
  net/http.serverHandler.ServeHTTP()
      /home/abi/go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      /home/abi/go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      /home/abi/go/src/net/http/server.go:3285 +0x4f

```

**Comment by abbbi** [comment]
my attempt to fix this would be to use a sync.Map for the ticket entries, which is save amongst goroutines.
Running the service with -race for quite some time doesnt report any races anymore.

Changes are here:

https://github.com/tizbac/pmoxs3backuproxy/compare/master...abbbi:pmoxs3backuproxy:sync_map

**Comment by tizbac** [comment]
I will check and merge tomorrow, thanks very much

Il dom 11 ago 2024, 19:30 Michael Ablassmeier ***@***.***> ha
scritto:

**Comment by tizbac** [comment]
Merged
