### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by abbbi** [tizbac/pmoxs3backuproxy#36]
another one where there is a race condition, its more commonly happening with dynamic index
because proxmox-backup client requests two writers at the exact same time, so i guess

 s.Writers[wid] 

needs to become a sync.Map too?

```
2024/08/19 10:28:19 [DEBUG] Request:/dynamic_index?archive-name=root.pxar.didx Method: POST
2024/08/19 10:28:19 [DEBUG] Request:/dynamic_index?archive-name=catalog.pcat1.didx Method: POST
fatal error: concurrent map writes

goroutine 422008 [running]:
main.(*Server).ServeHTTP(0xc000201ef0, {0x969bd8, 0xc000072d30}, 0xc000ba6480)
        /home/abi/pmoxs3backuproxy/cmd/pmoxs3backuproxy/main.go:401 +0x26d8
golang.org/x/net/http2.(*serverConn).runHandler(0xc61ec0?, 0x0?, 0x0?, 0xc000c80420?)
        /home/abi/go/pkg/mod/golang.org/x/net@v0.26.0/http2/server.go:2414 +0x113
created by golang.org/x/net/http2.(*serverConn).scheduleHandler in goroutine 422005
        /home/abi/go/pkg/mod/golang.org/x/net@v0.26.0/http2/server.go:2348 +0x21d
```

**Comment by tizbac** [comment]
Yes as i said all was made with the wrong assumption of go mutexes being intrinsically threadsafe
